name: Build Retype

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install
        run: npm install -g retypeapp

      - name: Build Retype
        run: |
          npx retype build
          mkdir -p public
          ls -la  
          touch public/.nojekyll  
      - name: Deploy to GH
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.retype
